class SimpleCoin {
  late String id;
  late String name;
  late String imageUrl;
  late String symbol;
  late String priceUsd;
  late String percentChange24h;
  bool inProfit;

  SimpleCoin(
      {required this.id,
      required this.name,
      required this.imageUrl,
      required this.symbol,
      required this.priceUsd,
      required this.inProfit,
      required this.percentChange24h});
}

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SparklineIn_7d {
/*
{
  "price": [
    50927.61393294162
  ]
} 
*/

  late List<double> price;

  SparklineIn_7d({
    required this.price,
  });
  SparklineIn_7d.fromJson(Map<String, dynamic> json) {
    if (json['price'] != null && (json['price'] is List)) {
      final v = json['price'];
      final arr0 = <double>[];
      v.forEach((v) {
        arr0.add((v)!);
      });
      price = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (price != null) {
      final v = price;
      final arr0 = [];
      v.forEach((v) {
        arr0.add(v);
      });
      data['price'] = arr0;
    }
    return data;
  }
}

class CoinGeckoCoinModel {
/*
{
  "id": "bitcoin",
  "symbol": "btc",
  "name": "Bitcoin",
  "image": "https://assets.coingecko.com/coins/images/1/large/bitcoin.png?1547033579",
  "current_price": 3521298,
  "market_cap": 66607181997303,
  "market_cap_rank": 1,
  "fully_diluted_valuation": 73947264988639,
  "total_volume": 1628319729713,
  "high_24h": 3573481,
  "low_24h": 3487173,
  "price_change_24h": 30208,
  "price_change_percentage_24h": 0.86529,
  "market_cap_change_24h": 605067346564,
  "market_cap_change_percentage_24h": 0.91674,
  "circulating_supply": 18915518,
  "total_supply": 21000000,
  "max_supply": 21000000,
  "ath": 5128383,
  "ath_change_percentage": -31.45966,
  "ath_date": "2021-11-10T14:24:11.849Z",
  "atl": 3993.42,
  "atl_change_percentage": 87920.07415,
  "atl_date": "2013-07-05T00:00:00.000Z",
  "roi": null,
  "last_updated": "2021-12-31T05:49:27.998Z",
  "sparkline_in_7d": {
    "price": [
      50927.61393294162
    ]
  },
  "price_change_percentage_7d_in_currency": -7.843226626355257
} 
*/

  late String id;
  late String symbol;
  late String name;
  late String image;
  late String currentPrice;
  late String marketCap;
  late String marketCapRank;
  late String fullyDilutedValuation;
  late String totalVolume;
  late String high_24h;
  late String low_24h;
  late String priceChange_24h;
  late String priceChangePercentage_24h;
  late String marketCapChange_24h;
  late String marketCapChangePercentage_24h;
  late String circulatingSupply;
  late String totalSupply;
  late String maxSupply;
  late String ath;
  late String athChangePercentage;
  late String athDate;
  late String atl;
  late String atlChangePercentage;
  late String atlDate;
  late String roi;
  late String lastUpdated;
  late SparklineIn_7d sparklineIn_7d;
  late String priceChangePercentage_7dInCurrency;

  CoinGeckoCoinModel({
    required this.id,
    required this.symbol,
    required this.name,
    required this.image,
    required this.currentPrice,
    required this.marketCap,
    required this.marketCapRank,
    required this.fullyDilutedValuation,
    required this.totalVolume,
    required this.high_24h,
    required this.low_24h,
    required this.priceChange_24h,
    required this.priceChangePercentage_24h,
    required this.marketCapChange_24h,
    required this.marketCapChangePercentage_24h,
    required this.circulatingSupply,
    required this.totalSupply,
    required this.maxSupply,
    required this.ath,
    required this.athChangePercentage,
    required this.athDate,
    required this.atl,
    required this.atlChangePercentage,
    required this.atlDate,
    required this.roi,
    required this.lastUpdated,
    required this.sparklineIn_7d,
    required this.priceChangePercentage_7dInCurrency,
  });
  CoinGeckoCoinModel.fromJson(Map<String, dynamic> json) {
    // print(json);
    id = json['id'].toString();
    symbol = json['symbol'].toString();
    name = json['name'].toString();
    image = json['image'].toString();
    currentPrice = json['current_price'].toString();
    marketCap = (json['market_cap'].toString());
    marketCapRank = (json['market_cap_rank'].toString());
    fullyDilutedValuation = (json['fully_diluted_valuation'].toString());
    totalVolume = (json['total_volume'].toString());
    high_24h = (json['high_24h'].toString());
    low_24h = (json['low_24h'].toString());
    priceChange_24h = (json['price_change_24h'].toString());
    priceChangePercentage_24h =
        (json['price_change_percentage_24h'].toString());
    marketCapChange_24h = (json['market_cap_change_24h'].toString());
    marketCapChangePercentage_24h =
        (json['market_cap_change_percentage_24h'].toString());
    circulatingSupply = (json['circulating_supply'].toString());
    totalSupply = (json['total_supply'].toString());
    maxSupply = (json['max_supply'].toString());
    ath = (json['ath'].toString());
    athChangePercentage = (json['ath_change_percentage'].toString());
    athDate = json['ath_date'].toString();
    atl = (json['atl'].toString());
    atlChangePercentage = (json['atl_change_percentage'].toString());
    atlDate = json['atl_date'].toString();
    roi = json['roi'].toString();
    lastUpdated = json['last_updated'].toString();
    sparklineIn_7d =
        ((json['sparkline_in_7d'] != null && (json['sparkline_in_7d'] is Map))
            ? SparklineIn_7d.fromJson(json['sparkline_in_7d'])
            : null)!;
    priceChangePercentage_7dInCurrency =
        (json['price_change_percentage_7d_in_currency'].toString());
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['symbol'] = symbol;
    data['name'] = name;
    data['image'] = image;
    data['current_price'] = currentPrice;
    data['market_cap'] = marketCap;
    data['market_cap_rank'] = marketCapRank;
    data['fully_diluted_valuation'] = fullyDilutedValuation;
    data['total_volume'] = totalVolume;
    data['high_24h'] = high_24h;
    data['low_24h'] = low_24h;
    data['price_change_24h'] = priceChange_24h;
    data['price_change_percentage_24h'] = priceChangePercentage_24h;
    data['market_cap_change_24h'] = marketCapChange_24h;
    data['market_cap_change_percentage_24h'] = marketCapChangePercentage_24h;
    data['circulating_supply'] = circulatingSupply;
    data['total_supply'] = totalSupply;
    data['max_supply'] = maxSupply;
    data['ath'] = ath;
    data['ath_change_percentage'] = athChangePercentage;
    data['ath_date'] = athDate;
    data['atl'] = atl;
    data['atl_change_percentage'] = atlChangePercentage;
    data['atl_date'] = atlDate;
    data['roi'] = roi;
    data['last_updated'] = lastUpdated;
    if (sparklineIn_7d != null) {
      data['sparkline_in_7d'] = sparklineIn_7d.toJson();
    }
    data['price_change_percentage_7d_in_currency'] =
        priceChangePercentage_7dInCurrency;
    return data;
  }
}
